// @jrm/tailwind-preset — a ready-to-use Tailwind preset for JRM Studio.
//
// The preset itself — token values, dark-mode strategy, container, radius aliases,
// ring width, safe-area spacing, and the fade/pop animations — is generated by
// @jrm/tokens, so it lives in exactly one place and cannot drift from the tokens.
//
// This package adds only the one thing a generated data file cannot carry: the
// `tailwindcss-animate` plugin instance. Consumers who install from npm get the
// convenience; consumers who receive `vendor/@jrm/tokens` as a synced directory
// point Tailwind straight at `vendor/@jrm/tokens/tailwind/default.cjs` and get an
// identical preset minus the plugin.
//
//   // tailwind.config.js
//   module.exports = { presets: [require("@jrm/tailwind-preset")], content: [...] };

const tokensPreset = require('@jrm/tokens/tailwind');

/** @type {import('tailwindcss').Config} */
const preset = {
  ...tokensPreset,
  plugins: [require('tailwindcss-animate')],
};

module.exports = preset;
