// Native token output — Android (Jetpack Compose) and Apple (SwiftUI).
//
// Why this exists: Studio's tokens reached the web through CSS variables and a Tailwind
// preset, but native consumers had no distribution at all. finance's Android layer had
// hand-rolled a Compose theme built on a completely different palette, and its iOS layer
// had no token layer whatsoever. Both drifted precisely because there was nothing to
// consume.
//
// Design: this renders from the *resolved* per-mode token trees the Style Dictionary
// build already produces, so native output can never disagree with the CSS and JS
// output — there is one resolution pass, not three. Every theme ships in a single file
// per platform, because the sync engine mirrors `dist/` as a flat copied tree and a
// hundred-directory `.xcassets` catalog would be unreviewable in that form.
//
// The emitted code is deliberately plain data: value holders and a theme selector, with
// no opinion about how an app wires them into MaterialTheme or the SwiftUI environment.
// That is the native equivalent of "framework-neutral output".

const AUTOGEN_KT = '// Auto-generated by @jrm/tokens. Do not edit by hand.';

/** Theme keys in documented order; index 0 is the default (light) theme. */
export const NATIVE_MODES = Object.freeze([
  'light',
  'dark',
  'dark-oled',
  'high-contrast',
  'high-contrast-dark',
]);

/**
 * `['semantic','background','primary']` → `backgroundPrimary`, `2xl` → `xl2`, `4` → `step4`.
 *
 * Token names are CSS-shaped, and CSS permits identifiers that neither Kotlin nor Swift
 * does. Leading digits are the case Studio actually hits, in two shapes: a digit-prefixed
 * name (`spacing.2xl`) is reordered so the scale still reads, and a bare grid multiplier
 * (`spacing.4`) becomes `step4`, since reordering leaves nothing to lead with. Anything
 * else invalid throws, because generated code that does not compile is worse than a
 * failed build.
 */
const camel = (parts) => {
  const raw = parts
    .map((part, index) => {
      const words = String(part).split('-');
      return words
        .map((word, wordIndex) =>
          index === 0 && wordIndex === 0 ? word : word.charAt(0).toUpperCase() + word.slice(1),
        )
        .join('');
    })
    .join('');

  // `2xl` → `xl2`: move a leading numeric run to the end, preserving the scale reading.
  // `4` → `step4`: an all-digit name has no remainder to lead with, so it is prefixed.
  const identifier = /^\d+$/.test(raw)
    ? `step${raw}`
    : raw.replace(/^(\d+)(.*)$/, (_, digits, rest) => `${rest}${digits}`);

  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(identifier) || RESERVED.has(identifier)) {
    throw new Error(
      `Native output cannot name token "${parts.join('.')}" (produced "${identifier}").`,
    );
  }
  return identifier;
};

/** Keywords that are reserved in Kotlin or Swift in a declaration position. */
const RESERVED = new Set([
  'as',
  'break',
  'case',
  'catch',
  'class',
  'continue',
  'default',
  'do',
  'else',
  'enum',
  'extension',
  'false',
  'for',
  'fun',
  'func',
  'if',
  'import',
  'in',
  'init',
  'interface',
  'internal',
  'is',
  'let',
  'null',
  'object',
  'operator',
  'package',
  'private',
  'protocol',
  'public',
  'return',
  'self',
  'static',
  'struct',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typealias',
  'val',
  'var',
  'when',
  'where',
  'while',
]);

/** `dark-oled` → `DarkOled`. */
const pascalMode = (mode) =>
  mode
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

const flatten = (node, prefix = []) => {
  const out = [];
  for (const [key, value] of Object.entries(node ?? {})) {
    if (value && typeof value === 'object') out.push(...flatten(value, [...prefix, key]));
    else out.push([[...prefix, key], value]);
  }
  return out;
};

/**
 * `#rgb`, `#rrggbb`, `#rrggbbaa`, and `oklch(L C H[ / A])` → `{ r, g, b, a }` as 0–255 ints.
 *
 * Studio authors a meaningful share of its palette in OKLCH, because perceptually uniform
 * lightness is what makes the high-contrast theme derivable rather than hand-tuned. Native
 * platforms have no OKLCH literal, so this converts rather than rejects — dropping those
 * colors would silently hand native consumers an incomplete theme, which is exactly the
 * gap this output exists to close.
 *
 * A color that still cannot be expressed fails the build here, once, rather than producing
 * code that does not compile.
 */
export function parseColor(value, path) {
  const raw = String(value).trim();

  const oklch = /^oklch\(\s*([\d.]+%?)\s+([\d.]+)\s+([\d.]+)\s*(?:\/\s*([\d.]+%?)\s*)?\)$/i.exec(
    raw,
  );
  if (oklch) return oklchToSrgb(oklch, path);

  const match = /^#([0-9a-fA-F]{3,8})$/.exec(raw);
  if (!match) throw new Error(`Native output cannot express color "${path}" (${raw}).`);

  let hex = match[1];
  if (hex.length === 3 || hex.length === 4) hex = [...hex].map((c) => c + c).join('');
  if (hex.length !== 6 && hex.length !== 8) {
    throw new Error(`Native output cannot express color "${path}" (${raw}).`);
  }

  const int = (offset) => Number.parseInt(hex.slice(offset, offset + 2), 16);
  return { r: int(0), g: int(2), b: int(4), a: hex.length === 8 ? int(6) : 255 };
}

const clamp01 = (value) => Math.min(1, Math.max(0, value));

/** Linear-light sRGB → gamma-encoded sRGB (IEC 61966-2-1). */
const gammaEncode = (channel) =>
  channel <= 0.0031308 ? 12.92 * channel : 1.055 * Math.pow(channel, 1 / 2.4) - 0.055;

/**
 * OKLCH → sRGB, via Oklab and linear sRGB (Björn Ottosson's published matrices).
 * Out-of-gamut results are clamped per channel, matching how browsers render these
 * same values on sRGB displays.
 */
function oklchToSrgb([, rawL, rawC, rawH, rawAlpha], path) {
  const asNumber = (text) =>
    text.endsWith('%') ? Number.parseFloat(text) / 100 : Number.parseFloat(text);

  const L = asNumber(rawL);
  const C = Number.parseFloat(rawC);
  const hue = (Number.parseFloat(rawH) * Math.PI) / 180;
  const alpha = rawAlpha === undefined ? 1 : asNumber(rawAlpha);

  if (![L, C, hue, alpha].every(Number.isFinite)) {
    throw new Error(`Native output cannot express color "${path}".`);
  }

  const a = C * Math.cos(hue);
  const b = C * Math.sin(hue);

  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;

  const linear = [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];

  const [r, g, blue] = linear.map((channel) => Math.round(clamp01(gammaEncode(channel)) * 255));
  return { r, g, b: blue, a: Math.round(clamp01(alpha) * 255) };
}

/** Strip a `px`/`ms` unit and return a finite number, or throw. */
const numeric = (value, path) => {
  const parsed = Number.parseFloat(String(value));
  if (!Number.isFinite(parsed)) {
    throw new Error(`Native output cannot express dimension "${path}" (${value}).`);
  }
  return parsed;
};

/**
 * The type scale is authored in `rem`, which has no native equivalent — native
 * platforms scale text through the user's own accessibility setting instead. Resolve
 * against the CSS root default so `1rem` lands on the platform-conventional 16sp/16pt
 * rather than a nonsensical 1.
 */
const ROOT_FONT_PX = 16;
const fontNumeric = (value, path) => {
  const parsed = numeric(value, path);
  return String(value).trim().endsWith('rem') ? parsed * ROOT_FONT_PX : parsed;
};

/** Trim trailing zeros so 6 → "6" and 0.38 → "0.38"; keeps output byte-stable. */
const num = (value) => String(Number(value.toFixed(4)));

/**
 * Collect the scalar groups that every platform shares. These are theme-agnostic, so
 * they are emitted once rather than per theme.
 */
function scalarGroups(tree) {
  const group = (key) => flatten(tree[key] ?? {});
  return {
    spacing: group('spacing'),
    radius: group('radius'),
    fontSize: flatten(tree.font?.size ?? {}),
    target: group('target'),
    focus: group('focus'),
    opacity: group('opacity'),
    layer: group('layer'),
    duration: group('duration'),
  };
}

/** Semantic colors, in the documented order, shared by every theme (parity is enforced). */
const semanticColors = (tree) => flatten(tree.semantic ?? {});

function assertParity(trees) {
  const reference = semanticColors(trees[NATIVE_MODES[0]]).map(([path]) => path.join('.'));
  for (const mode of NATIVE_MODES.slice(1)) {
    const actual = semanticColors(trees[mode]).map(([path]) => path.join('.'));
    if (actual.length !== reference.length || actual.some((p, i) => p !== reference[i])) {
      throw new Error(`Native output requires identical semantic keys; "${mode}" differs.`);
    }
  }
  return reference;
}

// ---------------------------------------------------------------------------
// Android — Jetpack Compose
// ---------------------------------------------------------------------------

export function renderCompose(trees, packageName = 'dev.jrm.tokens') {
  assertParity(trees);
  const colors = semanticColors(trees[NATIVE_MODES[0]]);
  const scalars = scalarGroups(trees[NATIVE_MODES[0]]);

  const composeColor = ({ r, g, b, a }) => {
    const hex = [a, r, g, b].map((c) => c.toString(16).padStart(2, '0')).join('');
    return `Color(0x${hex.toUpperCase()})`;
  };

  const schemeFields = colors.map(([path]) => `    val ${camel(path)}: Color,`).join('\n');

  const schemeFor = (mode) => {
    const modeColors = semanticColors(trees[mode]);
    const body = modeColors
      .map(
        ([path, value]) =>
          `    ${camel(path)} = ${composeColor(parseColor(value, `${mode}:${path.join('.')}`))},`,
      )
      .join('\n');
    return `val Jrm${pascalMode(mode)}Colors: JrmColorScheme = JrmColorScheme(\n${body}\n)`;
  };

  const dpObject = (name, entries) =>
    `object ${name} {\n${entries
      .map(
        ([path, value]) => `    val ${camel(path)}: Dp = ${num(numeric(value, path.join('.')))}.dp`,
      )
      .join('\n')}\n}`;

  const floatObject = (name, entries) =>
    `object ${name} {\n${entries
      .map(
        ([path, value]) =>
          `    const val ${camel(path)}: Float = ${num(numeric(value, path.join('.')))}f`,
      )
      .join('\n')}\n}`;

  return `${AUTOGEN_KT}
package ${packageName}

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** The theme-varying semantic color contract. Every theme defines every field. */
data class JrmColorScheme(
${schemeFields}
)

${NATIVE_MODES.map(schemeFor).join('\n\n')}

/** The documented themes. [Light] is the default. */
enum class JrmTheme {
${NATIVE_MODES.map((mode) => `    ${pascalMode(mode)},`).join('\n')}
}

fun jrmColorScheme(theme: JrmTheme): JrmColorScheme = when (theme) {
${NATIVE_MODES.map((mode) => `    JrmTheme.${pascalMode(mode)} -> Jrm${pascalMode(mode)}Colors`).join('\n')}
}

${dpObject('JrmSpacing', scalars.spacing)}

${dpObject('JrmRadius', scalars.radius)}

${dpObject('JrmTarget', scalars.target)}

${dpObject('JrmFocus', scalars.focus)}

object JrmFontSize {
${scalars.fontSize
  .map(
    ([path, value]) =>
      `    val ${camel(path)}: TextUnit = ${num(fontNumeric(value, path.join('.')))}.sp`,
  )
  .join('\n')}
}

${floatObject('JrmOpacity', scalars.opacity)}

${floatObject('JrmLayer', scalars.layer)}

/** Motion durations in milliseconds. */
object JrmDuration {
${scalars.duration
  .map(
    ([path, value]) =>
      `    const val ${camel(path)}: Int = ${Math.round(numeric(value, path.join('.')))}`,
  )
  .join('\n')}
}
`;
}

// ---------------------------------------------------------------------------
// Apple — SwiftUI
// ---------------------------------------------------------------------------

export function renderSwift(trees) {
  assertParity(trees);
  const colors = semanticColors(trees[NATIVE_MODES[0]]);
  const scalars = scalarGroups(trees[NATIVE_MODES[0]]);

  const swiftColor = ({ r, g, b, a }) =>
    `Color(red: ${num(r / 255)}, green: ${num(g / 255)}, blue: ${num(b / 255)}, opacity: ${num(a / 255)})`;

  const schemeFields = colors.map(([path]) => `    public let ${camel(path)}: Color`).join('\n');

  const initParams = colors.map(([path]) => `${camel(path)}: Color`).join(',\n        ');
  const initAssigns = colors
    .map(([path]) => `        self.${camel(path)} = ${camel(path)}`)
    .join('\n');

  const schemeFor = (mode) => {
    const body = semanticColors(trees[mode])
      .map(
        ([path, value]) =>
          `        ${camel(path)}: ${swiftColor(parseColor(value, `${mode}:${path.join('.')}`))}`,
      )
      .join(',\n');
    const name = pascalMode(mode);
    return `    public static let ${name.charAt(0).toLowerCase() + name.slice(1)} = JRMColorScheme(\n${body}\n    )`;
  };

  const cgFloatEnum = (name, entries, doc, convert = numeric) =>
    `${doc}\npublic enum ${name} {\n${entries
      .map(
        ([path, value]) =>
          `    public static let ${camel(path)}: CGFloat = ${num(convert(value, path.join('.')))}`,
      )
      .join('\n')}\n}`;

  return `${AUTOGEN_KT}
import SwiftUI

/// The theme-varying semantic color contract. Every theme defines every field.
public struct JRMColorScheme: Equatable {
${schemeFields}

    public init(
        ${initParams}
    ) {
${initAssigns}
    }
}

extension JRMColorScheme {
${NATIVE_MODES.map(schemeFor).join('\n\n')}
}

/// The documented themes. Light is the default.
public enum JRMTheme: String, CaseIterable, Sendable {
${NATIVE_MODES.map((mode) => {
  const name = pascalMode(mode);
  return `    case ${name.charAt(0).toLowerCase() + name.slice(1)} = "${mode}"`;
}).join('\n')}

    public var colors: JRMColorScheme {
        switch self {
${NATIVE_MODES.map((mode) => {
  const name = pascalMode(mode);
  const camelName = name.charAt(0).toLowerCase() + name.slice(1);
  return `        case .${camelName}: return .${camelName}`;
}).join('\n')}
        }
    }
}

${cgFloatEnum('JRMSpacing', scalars.spacing, '/// Spacing scale, in points.')}

${cgFloatEnum('JRMRadius', scalars.radius, '/// Corner radius scale, in points.')}

${cgFloatEnum('JRMTarget', scalars.target, '/// Minimum hit-target sizes, in points.')}

${cgFloatEnum('JRMFocus', scalars.focus, '/// Focus ring metrics, in points.')}

${cgFloatEnum('JRMFontSize', scalars.fontSize, '/// Type scale, in points.', fontNumeric)}

${cgFloatEnum('JRMOpacity', scalars.opacity, '/// Opacity ramp.')}

${cgFloatEnum('JRMLayer', scalars.layer, '/// Stacking order for zIndex.')}

/// Motion durations, in seconds.
public enum JRMDuration {
${scalars.duration
  .map(
    ([path, value]) =>
      `    public static let ${camel(path)}: TimeInterval = ${num(numeric(value, path.join('.')) / 1000)}`,
  )
  .join('\n')}
}
`;
}
