// @jrm/tokens — Style Dictionary v5 build.
//
// Produces THREE framework-agnostic outputs per theme (default), each covering
// light / dark / high-contrast color modes:
//   (a) CSS custom properties  → build/css/default/*.css
//   (b) a Tailwind preset object → build/tailwind/default.cjs
//   (c) typed JS/TS token objects → build/js/default/*.{js,d.ts}
//
// Model: primitive → semantic → component (DTCG $value/$type + {ref} aliases).
// Light is the CSS :root default; dark & high-contrast are [data-theme] overrides.
// Dark is the canonical narrative mode (the app boots data-theme="dark").

import StyleDictionary from 'style-dictionary';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { mkdirSync, writeFileSync } from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const toGlob = (p) => p.replace(/\\/g, '/');
const norm = (p) => (p || '').replace(/\\/g, '/');

const THEME = 'default'; // studio-wide provisional theme (values seeded from score-king)
const themeDir = toGlob(join(root, 'tokens', 'themes', THEME));

// ---------------------------------------------------------------------------
// Source sets
// ---------------------------------------------------------------------------

const primitives = toGlob(join(root, 'tokens', 'primitive', '*.json'));
const colorPrimitive = `${themeDir}/color.primitive.json`;
const semLight = `${themeDir}/color.semantic.light.json`;
const semDark = `${themeDir}/color.semantic.dark.json`;
const semHighContrast = `${themeDir}/color.semantic.high-contrast.json`;

/** Theme-agnostic semantic tokens (typography + motion purposes). */
const sharedSemantic = [
  toGlob(join(root, 'tokens', 'semantic', 'typography.json')),
  toGlob(join(root, 'tokens', 'semantic', 'motion.json')),
];

const components = toGlob(join(root, 'tokens', 'component', '*.json'));

const sourceFor = (semanticColorFile) => [
  primitives,
  colorPrimitive,
  semanticColorFile,
  ...sharedSemantic,
  components,
];

const cssBuildPath = toGlob(join(root, 'build', 'css', THEME)) + '/';
const jsBuildPath = toGlob(join(root, 'build', 'js', THEME)) + '/';
const tailwindBuildPath = toGlob(join(root, 'build', 'tailwind')) + '/';

// ---------------------------------------------------------------------------
// Custom transforms & groups (values emitted verbatim — no rem/color rewriting)
// ---------------------------------------------------------------------------

StyleDictionary.registerTransform({
  name: 'jrm/fontFamily/css',
  type: 'value',
  transitive: true,
  filter: (token) => token.$type === 'fontFamily',
  transform: (token) => {
    const v = token.$value ?? token.value;
    return Array.isArray(v) ? v.join(', ') : v;
  },
});

// CSS: kebab names + font-family join; every other value stays exactly as authored.
StyleDictionary.registerTransformGroup({
  name: 'jrm/css',
  transforms: ['attribute/cti', 'name/kebab', 'jrm/fontFamily/css'],
});

// JS: unique kebab names (silences name-collision detection) — values are NOT
// rewritten, and the JS/Tailwind formats key off token.path, so output is unaffected.
StyleDictionary.registerTransformGroup({
  name: 'jrm/js',
  transforms: ['attribute/cti', 'name/kebab'],
});

// ---------------------------------------------------------------------------
// Custom formats: typed JS module + .d.ts, and the Tailwind preset object
// ---------------------------------------------------------------------------

const AUTOGEN = '// Auto-generated by Style Dictionary. Do not edit by hand.';

/** Rebuild the nested token tree (by path) with fully-resolved values. */
function buildTree(allTokens) {
  const tree = {};
  for (const token of allTokens) {
    const value = token.$value ?? token.value;
    const path = token.path;
    let node = tree;
    for (let i = 0; i < path.length - 1; i += 1) {
      node[path[i]] ??= {};
      node = node[path[i]];
    }
    node[path[path.length - 1]] = value;
  }
  return tree;
}

/** Emit a precise `as const`-style literal type for the token tree. */
function dtsType(node) {
  if (Array.isArray(node)) {
    return `readonly [${node.map((v) => JSON.stringify(v)).join(', ')}]`;
  }
  if (node && typeof node === 'object') {
    const entries = Object.entries(node).map(
      ([k, v]) => `readonly ${JSON.stringify(k)}: ${dtsType(v)}`,
    );
    return `{ ${entries.join('; ')} }`;
  }
  return JSON.stringify(node);
}

StyleDictionary.registerFormat({
  name: 'jrm/js-module',
  format: ({ dictionary }) => {
    const tree = buildTree(dictionary.allTokens);
    return `${AUTOGEN}\nexport const tokens = ${JSON.stringify(tree, null, 2)};\nexport default tokens;\n`;
  },
});

StyleDictionary.registerFormat({
  name: 'jrm/js-dts',
  format: ({ dictionary }) => {
    const tree = buildTree(dictionary.allTokens);
    return `${AUTOGEN}\nexport declare const tokens: ${dtsType(tree)};\nexport default tokens;\n`;
  },
});

/**
 * Tailwind preset object whose values are `var(--…)` references, so a runtime
 * theme/mode swap (changing `data-theme`) re-flows every utility with no rebuild.
 * Semantic color names are aliased to Tailwind-ergonomic keys.
 */
StyleDictionary.registerFormat({
  name: 'jrm/tailwind-preset',
  format: ({ dictionary }) => {
    const varRef = (path) => `var(--${path.join('-')})`;
    const colorAlias = {
      text: 'foreground',
      'text-muted': 'muted',
      bg: 'background',
      'focus-ring': 'ring',
      'on-primary': 'primary-foreground',
    };

    const colors = {};
    const spacing = {};
    const borderRadius = {};
    const boxShadow = {};
    const fontSize = {};
    const fontFamily = {};

    for (const token of dictionary.allTokens) {
      const [group, ...rest] = token.path;
      const fromLightSemantic = norm(token.filePath).endsWith('color.semantic.light.json');

      if (group === 'color') {
        if (rest[0] === 'player') {
          colors.player ??= {};
          colors.player[rest[1]] = varRef(token.path);
        } else if (fromLightSemantic) {
          const key = rest.join('-');
          colors[colorAlias[key] ?? key] = varRef(token.path);
        }
        continue;
      }
      if (group === 'radius') {
        borderRadius[rest.join('-')] = varRef(token.path);
        continue;
      }
      if (group === 'spacing') {
        spacing[rest.join('-')] = varRef(token.path);
        continue;
      }
      if (group === 'shadow' && fromLightSemantic) {
        boxShadow[rest.join('-')] = varRef(token.path);
        continue;
      }
      if (group === 'font' && rest[0] === 'size') {
        fontSize[rest[1]] = varRef(token.path);
        continue;
      }
      if (group === 'font' && rest[0] === 'family') {
        fontFamily[rest[1]] = [varRef(token.path)];
        continue;
      }
    }

    const preset = {
      theme: { extend: { colors, spacing, borderRadius, boxShadow, fontSize, fontFamily } },
    };
    return `${AUTOGEN}\nmodule.exports = ${JSON.stringify(preset, null, 2)};\n`;
  },
});

// ---------------------------------------------------------------------------
// Platform builders
// ---------------------------------------------------------------------------

const jsFiles = (mode) => ({
  transformGroup: 'jrm/js',
  buildPath: jsBuildPath,
  files: [
    { destination: `tokens.${mode}.js`, format: 'jrm/js-module' },
    { destination: `tokens.${mode}.d.ts`, format: 'jrm/js-dts' },
  ],
});

/** Root (:root) build for the light/default mode — every tier, references kept. */
const lightSd = new StyleDictionary({
  source: sourceFor(semLight),
  usesDtcg: true,
  platforms: {
    css: {
      transformGroup: 'jrm/css',
      buildPath: cssBuildPath,
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: { outputReferences: true },
        },
      ],
    },
    js: jsFiles('light'),
    tailwind: {
      transformGroup: 'jrm/js',
      buildPath: tailwindBuildPath,
      files: [{ destination: `${THEME}.cjs`, format: 'jrm/tailwind-preset' }],
    },
  },
});

/** Theme-override build: emits ONLY that mode's semantic color+shadow overrides. */
const overrideSd = (mode, semanticColorFile, selector) =>
  new StyleDictionary({
    source: sourceFor(semanticColorFile),
    usesDtcg: true,
    platforms: {
      css: {
        transformGroup: 'jrm/css',
        buildPath: cssBuildPath,
        files: [
          {
            destination: `tokens-${mode}.css`,
            format: 'css/variables',
            options: { outputReferences: false, selector },
            filter: (token) => norm(token.filePath).endsWith(`color.semantic.${mode}.json`),
          },
        ],
      },
      js: jsFiles(mode),
    },
  });

const darkSd = overrideSd('dark', semDark, '[data-theme="dark"]');
const highContrastSd = overrideSd('high-contrast', semHighContrast, '[data-theme="high-contrast"]');

// ---------------------------------------------------------------------------
// Barrel files (not token-derived — stable wiring around the generated output)
// ---------------------------------------------------------------------------

function writeBarrels() {
  mkdirSync(cssBuildPath, { recursive: true });
  mkdirSync(jsBuildPath.replace(`${THEME}/`, ''), { recursive: true });

  // CSS barrel: import all modes, then collapse motion under reduced-motion.
  const indexCss = `${AUTOGEN.replace('//', '/*') } */
@import './tokens.css';
@import './tokens-dark.css';
@import './tokens-high-contrast.css';

@media (prefers-reduced-motion: reduce) {
  :root {
    --motion-press-duration: 0ms;
    --motion-state-duration: 0ms;
    --motion-tile-duration: 0ms;
  }
}
`;
  writeFileSync(join(root, 'build', 'css', THEME, 'index.css'), indexCss);

  // JS barrel: default = light (matches :root); named exports for every mode.
  const jsIndexDir = join(root, 'build', 'js');
  const indexJs = `${AUTOGEN}
import light from './${THEME}/tokens.light.js';
import dark from './${THEME}/tokens.dark.js';
import highContrast from './${THEME}/tokens.high-contrast.js';

export const tokens = light;
export const tokensLight = light;
export const tokensDark = dark;
export const tokensHighContrast = highContrast;
export const themes = { light, dark, 'high-contrast': highContrast };

export default tokens;
`;
  writeFileSync(join(jsIndexDir, 'index.js'), indexJs);

  const indexDts = `${AUTOGEN}
import light from './${THEME}/tokens.light.js';
import dark from './${THEME}/tokens.dark.js';
import highContrast from './${THEME}/tokens.high-contrast.js';

export declare const tokens: typeof light;
export declare const tokensLight: typeof light;
export declare const tokensDark: typeof dark;
export declare const tokensHighContrast: typeof highContrast;
export declare const themes: {
  readonly light: typeof light;
  readonly dark: typeof dark;
  readonly 'high-contrast': typeof highContrast;
};

export default tokens;
`;
  writeFileSync(join(jsIndexDir, 'index.d.ts'), indexDts);
}

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

try {
  await lightSd.buildAllPlatforms();
  await darkSd.buildAllPlatforms();
  await highContrastSd.buildAllPlatforms();
  writeBarrels();
  console.log(`✅ @jrm/tokens built (${THEME}: light + dark + high-contrast → css, tailwind, js).`);
} catch (err) {
  console.error('Build failed:', err);
  process.exit(1);
}
