// @jrm/tokens — Style Dictionary v5 build.
//
// Produces THREE framework-agnostic outputs per theme (default), each covering
// light / dark / high-contrast color modes:
//   (a) CSS custom properties  → build/css/default/*.css
//   (b) a Tailwind preset object → build/tailwind/default.cjs
//   (c) typed JS/TS token objects → build/js/default/*.{js,d.ts}
//
// Model: primitive → semantic → component (DTCG $value/$type + {ref} aliases).
// Light is the CSS :root default; dark & high-contrast are [data-theme] overrides.
// Dark is the canonical narrative mode (the app boots data-theme="dark").

import StyleDictionary from 'style-dictionary';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { mkdirSync, writeFileSync, readFileSync } from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const toGlob = (p) => p.replace(/\\/g, '/');
const norm = (p) => (p || '').replace(/\\/g, '/');

const THEME = 'default'; // studio-wide provisional theme (values seeded from score-king)
const themeDir = toGlob(join(root, 'tokens', 'themes', THEME));

// ---------------------------------------------------------------------------
// Source sets
// ---------------------------------------------------------------------------

const primitives = toGlob(join(root, 'tokens', 'primitive', '*.json'));
const colorPrimitive = `${themeDir}/color.primitive.json`;
const colorAliasFile = `${themeDir}/color.alias.json`;
const semLight = `${themeDir}/color.semantic.light.json`;
const semDark = `${themeDir}/color.semantic.dark.json`;
const semDarkOled = `${themeDir}/color.semantic.dark-oled.json`;
const semHighContrast = `${themeDir}/color.semantic.high-contrast.json`;

/** Theme-agnostic semantic tokens (typography + motion + cognitive purposes). */
const sharedSemantic = [
  toGlob(join(root, 'tokens', 'semantic', 'typography.json')),
  toGlob(join(root, 'tokens', 'semantic', 'motion.json')),
  toGlob(join(root, 'tokens', 'semantic', 'cognitive.json')),
];

const components = toGlob(join(root, 'tokens', 'component', '*.json'));

const sourceFor = (semanticColorFile) => [
  primitives,
  colorPrimitive,
  semanticColorFile,
  ...sharedSemantic,
  components,
];

const cssBuildPath = toGlob(join(root, 'build', 'css', THEME)) + '/';
const jsBuildPath = toGlob(join(root, 'build', 'js', THEME)) + '/';
const tailwindBuildPath = toGlob(join(root, 'build', 'tailwind')) + '/';

// ---------------------------------------------------------------------------
// Custom transforms & groups (values emitted verbatim — no rem/color rewriting)
// ---------------------------------------------------------------------------

StyleDictionary.registerTransform({
  name: 'jrm/fontFamily/css',
  type: 'value',
  transitive: true,
  filter: (token) => token.$type === 'fontFamily',
  transform: (token) => {
    const v = token.$value ?? token.value;
    return Array.isArray(v) ? v.join(', ') : v;
  },
});

// CSS: kebab names + font-family join; every other value stays exactly as authored.
StyleDictionary.registerTransformGroup({
  name: 'jrm/css',
  transforms: ['attribute/cti', 'name/kebab', 'jrm/fontFamily/css'],
});

// JS: unique kebab names (silences name-collision detection) — values are NOT
// rewritten, and the JS/Tailwind formats key off token.path, so output is unaffected.
StyleDictionary.registerTransformGroup({
  name: 'jrm/js',
  transforms: ['attribute/cti', 'name/kebab'],
});

// ---------------------------------------------------------------------------
// Custom formats: typed JS module + .d.ts, and the Tailwind preset object
// ---------------------------------------------------------------------------

const AUTOGEN = '// Auto-generated by Style Dictionary. Do not edit by hand.';

/** Rebuild the nested token tree (by path) with fully-resolved values. */
function buildTree(allTokens) {
  const tree = {};
  for (const token of allTokens) {
    const value = token.$value ?? token.value;
    const path = token.path;
    let node = tree;
    for (let i = 0; i < path.length - 1; i += 1) {
      node[path[i]] ??= {};
      node = node[path[i]];
    }
    node[path[path.length - 1]] = value;
  }
  return tree;
}

/** Emit a precise `as const`-style literal type for the token tree. */
function dtsType(node) {
  if (Array.isArray(node)) {
    return `readonly [${node.map((v) => JSON.stringify(v)).join(', ')}]`;
  }
  if (node && typeof node === 'object') {
    const entries = Object.entries(node).map(
      ([k, v]) => `readonly ${JSON.stringify(k)}: ${dtsType(v)}`,
    );
    return `{ ${entries.join('; ')} }`;
  }
  return JSON.stringify(node);
}

StyleDictionary.registerFormat({
  name: 'jrm/js-module',
  format: ({ dictionary }) => {
    const tree = buildTree(dictionary.allTokens);
    return `${AUTOGEN}\nexport const tokens = ${JSON.stringify(tree, null, 2)};\nexport default tokens;\n`;
  },
});

StyleDictionary.registerFormat({
  name: 'jrm/js-dts',
  format: ({ dictionary }) => {
    const tree = buildTree(dictionary.allTokens);
    return `${AUTOGEN}\nexport declare const tokens: ${dtsType(tree)};\nexport default tokens;\n`;
  },
});

/**
 * Tailwind preset object whose values are `var(--…)` references, so a runtime
 * theme/mode swap (changing `data-theme`) re-flows every utility with no rebuild.
 *
 * Exposes three color families:
 *   • flat back-compat keys (from color.alias.json) — `background`, `foreground`,
 *     `muted`, `primary`, `accent`, `danger`, … → `var(--color-*)`.
 *   • the full semantic taxonomy, nested under `semantic.*` (e.g.
 *     `bg-semantic-background-primary`) → `var(--semantic-*)`.
 *   • `player.*` and `chart.*` (incl. `chart.hc.*`) primitives.
 */
StyleDictionary.registerFormat({
  name: 'jrm/tailwind-preset',
  format: ({ dictionary }) => {
    const varRef = (path) => `var(--${path.join('-')})`;
    // Flat-alias → Tailwind-ergonomic key names (mirrors the legacy preset).
    const colorAlias = {
      text: 'foreground',
      'text-muted': 'muted',
      bg: 'background',
      'focus-ring': 'ring',
      'on-primary': 'primary-foreground',
    };

    const colors = {};
    const spacing = {};
    const borderRadius = {};
    const boxShadow = {};
    const fontSize = {};
    const fontFamily = {};

    const setDeep = (root, keys, value) => {
      let node = root;
      for (let i = 0; i < keys.length - 1; i += 1) {
        node[keys[i]] ??= {};
        node = node[keys[i]];
      }
      node[keys[keys.length - 1]] = value;
    };

    for (const token of dictionary.allTokens) {
      const [group, ...rest] = token.path;
      const file = norm(token.filePath);

      if (group === 'color') {
        if (rest[0] === 'player') {
          colors.player ??= {};
          colors.player[rest[1]] = varRef(token.path);
        } else if (rest[0] === 'chart') {
          setDeep(colors, ['chart', ...rest.slice(1)], varRef(token.path));
        } else if (file.endsWith('color.alias.json')) {
          const key = rest.join('-');
          colors[colorAlias[key] ?? key] = varRef(token.path);
        }
        continue;
      }
      if (group === 'semantic' && file.endsWith('color.semantic.light.json')) {
        setDeep(colors, ['semantic', ...rest], varRef(token.path));
        continue;
      }
      if (group === 'radius') {
        borderRadius[rest.join('-')] = varRef(token.path);
        continue;
      }
      if (group === 'spacing') {
        spacing[rest.join('-')] = varRef(token.path);
        continue;
      }
      if (group === 'shadow' && file.endsWith('color.semantic.light.json')) {
        boxShadow[rest.join('-')] = varRef(token.path);
        continue;
      }
      if (group === 'font' && rest[0] === 'size') {
        fontSize[rest[1]] = varRef(token.path);
        continue;
      }
      if (group === 'font' && rest[0] === 'family') {
        fontFamily[rest[1]] = [varRef(token.path)];
        continue;
      }
    }

    const preset = {
      theme: { extend: { colors, spacing, borderRadius, boxShadow, fontSize, fontFamily } },
    };
    return `${AUTOGEN}\nmodule.exports = ${JSON.stringify(preset, null, 2)};\n`;
  },
});

// ---------------------------------------------------------------------------
// Platform builders
// ---------------------------------------------------------------------------

const jsFiles = (mode) => ({
  transformGroup: 'jrm/js',
  buildPath: jsBuildPath,
  files: [
    { destination: `tokens.${mode}.js`, format: 'jrm/js-module' },
    { destination: `tokens.${mode}.d.ts`, format: 'jrm/js-dts' },
  ],
});

/** Root (:root) build for the light/default mode — every tier, references kept.
 *  Includes the flat back-compat alias file so the legacy `--color-*` names are
 *  declared once in :root and re-flow across every mode via the `--semantic-*` vars. */
const lightSd = new StyleDictionary({
  source: [...sourceFor(semLight), colorAliasFile],
  usesDtcg: true,
  platforms: {
    css: {
      transformGroup: 'jrm/css',
      buildPath: cssBuildPath,
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: { outputReferences: true },
        },
      ],
    },
    js: jsFiles('light'),
    tailwind: {
      transformGroup: 'jrm/js',
      buildPath: tailwindBuildPath,
      files: [{ destination: `${THEME}.cjs`, format: 'jrm/tailwind-preset' }],
    },
  },
});

/** Theme-override build: emits ONLY that mode's semantic color+shadow overrides. */
const overrideSd = (mode, semanticColorFile, selector) =>
  new StyleDictionary({
    source: sourceFor(semanticColorFile),
    usesDtcg: true,
    platforms: {
      css: {
        transformGroup: 'jrm/css',
        buildPath: cssBuildPath,
        files: [
          {
            destination: `tokens-${mode}.css`,
            format: 'css/variables',
            options: { outputReferences: false, selector },
            filter: (token) => norm(token.filePath).endsWith(`color.semantic.${mode}.json`),
          },
        ],
      },
      js: jsFiles(mode),
    },
  });

const darkSd = overrideSd('dark', semDark, '[data-theme="dark"]');
const darkOledSd = overrideSd('dark-oled', semDarkOled, '[data-theme="dark-oled"]');
const highContrastSd = overrideSd('high-contrast', semHighContrast, '[data-theme="high-contrast"]');

// ---------------------------------------------------------------------------
// Barrel files (not token-derived — stable wiring around the generated output)
// ---------------------------------------------------------------------------

/** `{color.ink.midnight}` → `--color-ink-midnight` (a var() target). */
const refToVar = (ref) => '--' + String(ref).replace(/[{}]/g, '').trim().split('.').join('-');

/**
 * Turn a semantic-mode JSON file into `--semantic-*: var(--<primitive>)` remap
 * lines. Used to port finance's consumer @media auto-switching into the package
 * output so consumers get preference-driven theming for free.
 */
function cssRemapLines(semanticFile, indent = '    ') {
  const json = JSON.parse(readFileSync(semanticFile, 'utf8'));
  const lines = [];
  const walk = (node, path) => {
    for (const [k, v] of Object.entries(node)) {
      if (k.startsWith('$')) continue;
      if (v && typeof v === 'object' && '$value' in v) {
        const name = '--' + [...path, k].join('-');
        const raw = v.$value;
        const val = typeof raw === 'string' && raw.startsWith('{') ? `var(${refToVar(raw)})` : raw;
        lines.push(`${indent}${name}: ${val};`);
      } else if (v && typeof v === 'object') {
        walk(v, [...path, k]);
      }
    }
  };
  if (json.semantic) walk(json.semantic, ['semantic']);
  if (json.shadow) walk(json.shadow, ['shadow']);
  return lines.join('\n');
}

/** Swap the generic chart ramp for its CVD-safe high-contrast variants. */
const chartHcRemap = (indent = '    ') =>
  [1, 2, 3, 4, 5, 6].map((n) => `${indent}--color-chart-${n}: var(--color-chart-hc-${n});`).join('\n');

function writeBarrels() {
  mkdirSync(cssBuildPath, { recursive: true });
  mkdirSync(jsBuildPath.replace(`${THEME}/`, ''), { recursive: true });

  const darkRemap = cssRemapLines(semDark);
  const highContrastRemap = cssRemapLines(semHighContrast);

  // CSS barrel: import every mode, then port finance's preference auto-switching.
  // Each @media block is guarded with :not([data-theme]) so an explicit theme wins.
  const indexCss = `${AUTOGEN.replace('//', '/*')} */
@import './tokens.css';
@import './tokens-dark.css';
@import './tokens-dark-oled.css';
@import './tokens-high-contrast.css';

/* Chart series swap to CVD-safe high-contrast variants under the explicit HC theme. */
[data-theme="high-contrast"] {
${chartHcRemap()}
}

/*
 * System preference: auto-apply the dark palette when the OS prefers dark and
 * the consumer has not pinned an explicit [data-theme].
 */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
${darkRemap}
  }
}

/*
 * prefers-contrast: more — promote the full high-contrast palette (WCAG 1.4.3 /
 * 1.4.6 / 1.4.11), including the high-contrast chart ramp.
 */
@media (prefers-contrast: more) {
  :root:not([data-theme]) {
${highContrastRemap}
${chartHcRemap()}
  }
}

/*
 * Dark + more contrast: brighter foregrounds and stronger borders on the dark
 * surfaces for users who want both.
 */
@media (prefers-color-scheme: dark) and (prefers-contrast: more) {
  :root:not([data-theme]) {
    --semantic-text-primary: var(--color-base-white);
    --semantic-text-secondary: var(--color-ink-moonlight);
    --semantic-text-inverse: var(--color-ink-midnight);
    --semantic-border-default: var(--color-ink-lavender-gray);
    --semantic-border-focus: var(--color-royal-violet-300);
    --semantic-border-error: var(--color-loss-300);
    --semantic-interactive-default: var(--color-royal-violet-300);
    --semantic-interactive-hover: var(--color-royal-violet-200);
    --semantic-interactive-pressed: var(--color-royal-violet-200);
    --semantic-status-positive: var(--color-win-500);
    --semantic-status-negative: var(--color-loss-400);
    --semantic-status-warning: var(--color-caution-500);
    --semantic-status-info: var(--color-info-300);
  }
}

/*
 * Reduced motion: collapse the underlying motion durations to instant.
 */
@media (prefers-reduced-motion: reduce) {
  :root {
    --motion-press-duration: 0ms;
    --motion-state-duration: 0ms;
    --motion-tile-duration: 0ms;
  }
}

/*
 * Cognitive-accessibility mode — activated by [data-a11y-cognitive="true"] on the
 * root element (finance's mechanism). Steps up the type scale, relaxes leading,
 * and disables motion (a superset of prefers-reduced-motion).
 */
[data-a11y-cognitive="true"] {
  --text-display-size: var(--cognitive-type-display-size);
  --text-display-line-height: var(--cognitive-type-display-line-height);
  --text-title-size: var(--cognitive-type-title-size);
  --text-title-line-height: var(--cognitive-type-title-line-height);
  --text-body-size: var(--cognitive-type-body-size);
  --text-body-line-height: var(--cognitive-type-body-line-height);
  --text-label-size: var(--cognitive-type-label-size);
  --text-label-line-height: var(--cognitive-type-label-line-height);
  --text-overline-size: var(--cognitive-type-overline-size);
  --text-overline-line-height: var(--cognitive-type-overline-line-height);

  --motion-press-duration: 0ms;
  --motion-state-duration: 0ms;
  --motion-tile-duration: 0ms;
}
`;
  writeFileSync(join(root, 'build', 'css', THEME, 'index.css'), indexCss);

  // JS barrel: default = light (matches :root); named exports for every mode.
  const jsIndexDir = join(root, 'build', 'js');
  const indexJs = `${AUTOGEN}
import light from './${THEME}/tokens.light.js';
import dark from './${THEME}/tokens.dark.js';
import darkOled from './${THEME}/tokens.dark-oled.js';
import highContrast from './${THEME}/tokens.high-contrast.js';

export const tokens = light;
export const tokensLight = light;
export const tokensDark = dark;
export const tokensDarkOled = darkOled;
export const tokensHighContrast = highContrast;
export const themes = { light, dark, 'dark-oled': darkOled, 'high-contrast': highContrast };

export default tokens;
`;
  writeFileSync(join(jsIndexDir, 'index.js'), indexJs);

  const indexDts = `${AUTOGEN}
import light from './${THEME}/tokens.light.js';
import dark from './${THEME}/tokens.dark.js';
import darkOled from './${THEME}/tokens.dark-oled.js';
import highContrast from './${THEME}/tokens.high-contrast.js';

export declare const tokens: typeof light;
export declare const tokensLight: typeof light;
export declare const tokensDark: typeof dark;
export declare const tokensDarkOled: typeof darkOled;
export declare const tokensHighContrast: typeof highContrast;
export declare const themes: {
  readonly light: typeof light;
  readonly dark: typeof dark;
  readonly 'dark-oled': typeof darkOled;
  readonly 'high-contrast': typeof highContrast;
};

export default tokens;
`;
  writeFileSync(join(jsIndexDir, 'index.d.ts'), indexDts);
}

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

try {
  await lightSd.buildAllPlatforms();
  await darkSd.buildAllPlatforms();
  await darkOledSd.buildAllPlatforms();
  await highContrastSd.buildAllPlatforms();
  writeBarrels();
  console.log(
    `✅ @jrm/tokens built (${THEME}: light + dark + dark-oled + high-contrast → css, tailwind, js).`,
  );
} catch (err) {
  console.error('Build failed:', err);
  process.exit(1);
}
